### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by szb512**
This will bump 10 dependencies to their newest version.

### CODE REVIEW

**Comment by smithad15** [comment]
Hi. Thanks for helping out with the project. Please reference #72 as it already includes version bumps for a significant number of packages

**Comment by szb512** [comment]
True. I am bumping a few more that #72 don't include.

**Comment by szb512** [comment]
Build fails because of this:
BUILD ERROR
The Angular Compiler requires TypeScript >=2.7.2 and <2.8.0 but 3.3.3333 was found instead.
Error: The Angular Compiler requires TypeScript >=2.7.2 and <2.8.0 but 3.3.3333 was found instead.
    at checkVersion (/home/circleci/repo/node_modules/@angular/compiler-cli/src/transformers/program.js:806:19)
    at new AngularCompilerProgram (/home/circleci/repo/node_modules/@angular/compiler-cli/src/transformers/program.js:109:13)
    at Object.createProgram (/home/circleci/repo/node_modules/@angular/compiler-cli/src/transformers/program.js:812:16)
    at Object.createProgram (/home/circleci/repo/node_modules/@angular/compiler-cli/src/ngtools_api2.js:36:26)
    at Object.transformSourceFiles (/home/circleci/repo/node_modules/ng-packagr/lib/ngc/transform-source-files.js:19:28)
    at MapSubscriber.exports.analyseSourcesTransform.rxjs_1.pipe.operators_1.map.graph [as project] (/home/circleci/repo/node_modules/ng-packagr/lib/ng-v5/init/analyse-sources.transform.js:43:55)
    at MapSubscriber._next (/home/circleci/repo/node_modules/rxjs/internal/operators/map.js:46:35)
    at MapSubscriber.Subscriber.next (/home/circleci/repo/node_modules/rxjs/internal/Subscriber.js:64:18)
    at SwitchMapSubscriber.notifyNext (/home/circleci/repo/node_modules/rxjs/internal/operators/switchMap.js:77:26)
    at InnerSubscriber._next (/home/circleci/repo/node_modules/rxjs/internal/InnerSubscriber.js:25:21)

**Comment by szb512** [comment]
#72

**Comment by szb512** [comment]
#72 [https://github.com/angular-redux/platform/pull/72](url)

**Comment by szb512** [comment]
Make that more than 10 dependencies.

**Comment by smithad15** [comment]
Closing as out of date

**Pull request closed without merging**
